
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 货币配置表
/// </summary>
public sealed partial class CurrencyConfig : Luban.BeanBase
{
    public CurrencyConfig() { }
    
    public CurrencyConfig(ByteBuf _buf) 
    {
        CurrencyType = (CurrencyType)_buf.ReadInt();
        BootyType = _buf.ReadInt();
        ItemNameID = _buf.ReadInt();
        Quality = (ColorQuality)_buf.ReadInt();
        ItemID = _buf.ReadInt();
        Icon = _buf.ReadString();
        NotEnoughTextID = _buf.ReadInt();
        DescTextID = _buf.ReadInt();
    }

    public static CurrencyConfig DeserializeCurrencyConfig(ByteBuf _buf)
    {
        return new CurrencyConfig(_buf);
    }

    /// <summary>
    /// 货币类型
    /// </summary>
    public CurrencyType CurrencyType;
    /// <summary>
    /// 掉落类型
    /// </summary>
    public int BootyType;
    /// <summary>
    /// 货币名称
    /// </summary>
    public int ItemNameID;
    /// <summary>
    /// 品质
    /// </summary>
    public ColorQuality Quality;
    /// <summary>
    /// 对应道具ID
    /// </summary>
    public int ItemID;
    /// <summary>
    /// 图标
    /// </summary>
    public string Icon;
    /// <summary>
    /// 货币不足提示文本ID
    /// </summary>
    public int NotEnoughTextID;
    /// <summary>
    /// 描述文本ID
    /// </summary>
    public int DescTextID;

    public const int __ID__ = -1781720365;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref CurrencyConfig other)
    {
        if (other == null)
        {
            other = new CurrencyConfig();
        }
        other.CurrencyType = CurrencyType;
        other.BootyType = BootyType;
        other.ItemNameID = ItemNameID;
        other.Quality = Quality;
        other.ItemID = ItemID;
        other.Icon = Icon;
        other.NotEnoughTextID = NotEnoughTextID;
        other.DescTextID = DescTextID;
    }

    public CurrencyConfig DeepCopy()
    {
        var other = new CurrencyConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "CurrencyType:" + CurrencyType + ","
        + "BootyType:" + BootyType + ","
        + "ItemNameID:" + ItemNameID + ","
        + "Quality:" + Quality + ","
        + "ItemID:" + ItemID + ","
        + "Icon:" + Icon + ","
        + "NotEnoughTextID:" + NotEnoughTextID + ","
        + "DescTextID:" + DescTextID + ","
        + "}";
    }
}
}

