
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 新手引导步骤配置表
/// </summary>
public sealed partial class GuideStepConfig : Luban.BeanBase
{
    public GuideStepConfig() { }
    
    public GuideStepConfig(ByteBuf _buf) 
    {
        GuideId = _buf.ReadInt();
        GroupId = _buf.ReadInt();
        StepId = _buf.ReadInt();
        NextStepId = _buf.ReadInt();
        NeedTween = _buf.ReadBool();
        StepType = (EGuideStepType)_buf.ReadInt();
        if(_buf.ReadBool()){ StepParam = global::GameProto.GuideStepParam.DeserializeGuideStepParam(_buf); } else { StepParam = null; }
        Skippable = _buf.ReadBool();
        SkipScope = (EGuideSkipScope)_buf.ReadInt();
        GuideType = (EGuideType)_buf.ReadInt();
        GuideTime = _buf.ReadFloat();
        InputMode = (EGuideInputMode)_buf.ReadInt();
        MaskShape = (EGuideMaskShape)_buf.ReadInt();
        MaskPos = global::GameProto.Pos.DeserializePos(_buf);
        MaskSize = global::GameProto.Size.DeserializeSize(_buf);
        MaskRadius = _buf.ReadFloat();
        MaskPadding = _buf.ReadFloat();
        ArrowMoveType = (EGuideArrowMoveType)_buf.ReadInt();
        ArrowStartPos = global::GameProto.Pos.DeserializePos(_buf);
        ArrowTargetPos = global::GameProto.Pos.DeserializePos(_buf);
        LoopDelayTime = _buf.ReadFloat();
        LoopMoveArrow = _buf.ReadBool();
        TipTextId = _buf.ReadInt();
        TipPlacement = (EGuideTipPlacement)_buf.ReadInt();
        TipsPos = global::GameProto.Pos.DeserializePos(_buf);
        TipsSize = global::GameProto.Size.DeserializeSize(_buf);
        TimeoutMs = _buf.ReadInt();
    }

    public static GuideStepConfig DeserializeGuideStepConfig(ByteBuf _buf)
    {
        return new GuideStepConfig(_buf);
    }

    /// <summary>
    /// 引导ID
    /// </summary>
    public int GuideId;
    /// <summary>
    /// 引导组ID
    /// </summary>
    public int GroupId;
    /// <summary>
    /// 步骤ID
    /// </summary>
    public int StepId;
    /// <summary>
    /// 下一步骤ID，0为结束
    /// </summary>
    public int NextStepId;
    /// <summary>
    /// 播放引导框动画
    /// </summary>
    public bool NeedTween;
    /// <summary>
    /// 步骤类型
    /// </summary>
    public EGuideStepType StepType;
    /// <summary>
    /// 步骤int类型参数
    /// </summary>
    public GuideStepParam? StepParam;
    /// <summary>
    /// 是否可跳过
    /// </summary>
    public bool Skippable;
    /// <summary>
    /// 跳过范围
    /// </summary>
    public EGuideSkipScope SkipScope;
    /// <summary>
    /// 引导类型
    /// </summary>
    public EGuideType GuideType;
    /// <summary>
    /// 引导时间
    /// </summary>
    public float GuideTime;
    /// <summary>
    /// 输入模式
    /// </summary>
    public EGuideInputMode InputMode;
    /// <summary>
    /// 遮罩形状
    /// </summary>
    public EGuideMaskShape MaskShape;
    /// <summary>
    /// 遮罩坐标X
    /// </summary>
    public Pos MaskPos;
    /// <summary>
    /// 宽
    /// </summary>
    public Size MaskSize;
    /// <summary>
    /// 圆角
    /// </summary>
    public float MaskRadius;
    /// <summary>
    /// 遮罩外扩
    /// </summary>
    public float MaskPadding;
    /// <summary>
    /// 引导手指移动类型
    /// </summary>
    public EGuideArrowMoveType ArrowMoveType;
    /// <summary>
    /// 起始位置
    /// </summary>
    public Pos ArrowStartPos;
    /// <summary>
    /// 手指基于目标中心点X偏移/目标位置
    /// </summary>
    public Pos ArrowTargetPos;
    /// <summary>
    /// 循环延迟播放时间
    /// </summary>
    public float LoopDelayTime;
    /// <summary>
    /// 循环播放
    /// </summary>
    public bool LoopMoveArrow;
    /// <summary>
    /// 提示文本ID，0为无
    /// </summary>
    public int TipTextId;
    /// <summary>
    /// 提示位置
    /// </summary>
    public EGuideTipPlacement TipPlacement;
    /// <summary>
    /// 提示位置X
    /// </summary>
    public Pos TipsPos;
    /// <summary>
    /// 宽
    /// </summary>
    public Size TipsSize;
    /// <summary>
    /// 超时毫秒，0为默认
    /// </summary>
    public int TimeoutMs;

    public const int __ID__ = -1248104150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref GuideStepConfig other)
    {
        if (other == null)
        {
            other = new GuideStepConfig();
        }
        other.GuideId = GuideId;
        other.GroupId = GroupId;
        other.StepId = StepId;
        other.NextStepId = NextStepId;
        other.NeedTween = NeedTween;
        other.StepType = StepType;
        other.StepParam = StepParam;
        other.Skippable = Skippable;
        other.SkipScope = SkipScope;
        other.GuideType = GuideType;
        other.GuideTime = GuideTime;
        other.InputMode = InputMode;
        other.MaskShape = MaskShape;
        other.MaskPos = MaskPos;
        other.MaskSize = MaskSize;
        other.MaskRadius = MaskRadius;
        other.MaskPadding = MaskPadding;
        other.ArrowMoveType = ArrowMoveType;
        other.ArrowStartPos = ArrowStartPos;
        other.ArrowTargetPos = ArrowTargetPos;
        other.LoopDelayTime = LoopDelayTime;
        other.LoopMoveArrow = LoopMoveArrow;
        other.TipTextId = TipTextId;
        other.TipPlacement = TipPlacement;
        other.TipsPos = TipsPos;
        other.TipsSize = TipsSize;
        other.TimeoutMs = TimeoutMs;
    }

    public GuideStepConfig DeepCopy()
    {
        var other = new GuideStepConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "GuideId:" + GuideId + ","
        + "GroupId:" + GroupId + ","
        + "StepId:" + StepId + ","
        + "NextStepId:" + NextStepId + ","
        + "NeedTween:" + NeedTween + ","
        + "StepType:" + StepType + ","
        + "StepParam:" + StepParam + ","
        + "Skippable:" + Skippable + ","
        + "SkipScope:" + SkipScope + ","
        + "GuideType:" + GuideType + ","
        + "GuideTime:" + GuideTime + ","
        + "InputMode:" + InputMode + ","
        + "MaskShape:" + MaskShape + ","
        + "MaskPos:" + MaskPos + ","
        + "MaskSize:" + MaskSize + ","
        + "MaskRadius:" + MaskRadius + ","
        + "MaskPadding:" + MaskPadding + ","
        + "ArrowMoveType:" + ArrowMoveType + ","
        + "ArrowStartPos:" + ArrowStartPos + ","
        + "ArrowTargetPos:" + ArrowTargetPos + ","
        + "LoopDelayTime:" + LoopDelayTime + ","
        + "LoopMoveArrow:" + LoopMoveArrow + ","
        + "TipTextId:" + TipTextId + ","
        + "TipPlacement:" + TipPlacement + ","
        + "TipsPos:" + TipsPos + ","
        + "TipsSize:" + TipsSize + ","
        + "TimeoutMs:" + TimeoutMs + ","
        + "}";
    }
}
}

