
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 新手引导组配置表
/// </summary>
public sealed partial class GuideGroupConfig : Luban.BeanBase
{
    public GuideGroupConfig() { }
    
    public GuideGroupConfig(ByteBuf _buf) 
    {
        GroupId = _buf.ReadInt();
        Priority = _buf.ReadInt();
        FirstStepId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PrerequisiteGuideIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PrerequisiteGuideIds.Add(_e0);}}
        ConditionKey = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ConditionParams = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ConditionParams.Add(_e0);}}
        LocalSave = _buf.ReadBool();
        ResumePolicy = (EGuideResumePolicy)_buf.ReadInt();
        FailurePolicy = (EGuideFailurePolicy)_buf.ReadInt();
        Enabled = _buf.ReadBool();
    }

    public static GuideGroupConfig DeserializeGuideGroupConfig(ByteBuf _buf)
    {
        return new GuideGroupConfig(_buf);
    }

    /// <summary>
    /// 引导组ID
    /// </summary>
    public int GroupId;
    /// <summary>
    /// 优先级
    /// </summary>
    public int Priority;
    /// <summary>
    /// 首步骤ID
    /// </summary>
    public int FirstStepId;
    /// <summary>
    /// 前置引导ID
    /// </summary>
    public System.Collections.Generic.List<int> PrerequisiteGuideIds;
    /// <summary>
    /// 开启条件Key
    /// </summary>
    public int ConditionKey;
    /// <summary>
    /// 开启条件参数
    /// </summary>
    public System.Collections.Generic.List<int> ConditionParams;
    /// <summary>
    /// 是否本地存档
    /// </summary>
    public bool LocalSave;
    /// <summary>
    /// 恢复策略
    /// </summary>
    public EGuideResumePolicy ResumePolicy;
    /// <summary>
    /// 故障策略
    /// </summary>
    public EGuideFailurePolicy FailurePolicy;
    /// <summary>
    /// 是否启用
    /// </summary>
    public bool Enabled;

    public const int __ID__ = -301038043;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref GuideGroupConfig other)
    {
        if (other == null)
        {
            other = new GuideGroupConfig();
        }
        other.GroupId = GroupId;
        other.Priority = Priority;
        other.FirstStepId = FirstStepId;
        other.PrerequisiteGuideIds = PrerequisiteGuideIds == null ? null : new System.Collections.Generic.List<int>(PrerequisiteGuideIds);
        other.ConditionKey = ConditionKey;
        other.ConditionParams = ConditionParams == null ? null : new System.Collections.Generic.List<int>(ConditionParams);
        other.LocalSave = LocalSave;
        other.ResumePolicy = ResumePolicy;
        other.FailurePolicy = FailurePolicy;
        other.Enabled = Enabled;
    }

    public GuideGroupConfig DeepCopy()
    {
        var other = new GuideGroupConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "GroupId:" + GroupId + ","
        + "Priority:" + Priority + ","
        + "FirstStepId:" + FirstStepId + ","
        + "PrerequisiteGuideIds:" + Luban.StringUtil.CollectionToString(PrerequisiteGuideIds) + ","
        + "ConditionKey:" + ConditionKey + ","
        + "ConditionParams:" + Luban.StringUtil.CollectionToString(ConditionParams) + ","
        + "LocalSave:" + LocalSave + ","
        + "ResumePolicy:" + ResumePolicy + ","
        + "FailurePolicy:" + FailurePolicy + ","
        + "Enabled:" + Enabled + ","
        + "}";
    }
}
}

