
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 怪物配置表
/// </summary>
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig() { }
    
    public MonsterConfig(ByteBuf _buf) 
    {
        MonsterID = _buf.ReadInt();
        ModelID = _buf.ReadInt();
        MonsterNameId = _buf.ReadInt();
        AttrID = _buf.ReadInt();
        Type = _buf.ReadByte();
        ModelScale = _buf.ReadFloat();
        DiedDestroyTime = _buf.ReadFloat();
        Level = _buf.ReadInt();
        Atk = _buf.ReadInt();
        Hp = _buf.ReadInt();
        IsShowHp = _buf.ReadBool();
        HpCount = _buf.ReadInt();
        MoveSpeed = _buf.ReadFloat();
        DropExp = _buf.ReadInt();
        DropItemID = _buf.ReadInt();
        DamageReduction = _buf.ReadInt();
        HpLengthRatio = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); DefaultAttr = new System.Collections.Generic.List<AttrModifuerData>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AttrModifuerData _e0;  _e0 = global::GameProto.AttrModifuerData.DeserializeAttrModifuerData(_buf); DefaultAttr.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Skills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Skills.Add(_e0);}}
        AttachSkill = _buf.ReadInt();
        AutoPlaySkill = _buf.ReadInt();
        AITaskID = _buf.ReadInt();
        OutLineWidth = _buf.ReadInt();
        OutLineColor = _buf.ReadString();
    }

    public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
    {
        return new MonsterConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int MonsterID;
    /// <summary>
    /// 模型ID
    /// </summary>
    public int ModelID;
    /// <summary>
    /// 模型名称
    /// </summary>
    public int MonsterNameId;
    /// <summary>
    /// 属性角标
    /// </summary>
    public int AttrID;
    /// <summary>
    /// 怪物类型
    /// </summary>
    public byte Type;
    /// <summary>
    /// 模型缩放倍率
    /// </summary>
    public float ModelScale;
    /// <summary>
    /// 死亡消失时间
    /// </summary>
    public float DiedDestroyTime;
    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 攻击
    /// </summary>
    public int Atk;
    /// <summary>
    /// 血量
    /// </summary>
    public int Hp;
    /// <summary>
    /// 是否显示头顶血条
    /// </summary>
    public bool IsShowHp;
    /// <summary>
    /// 血条数量
    /// </summary>
    public int HpCount;
    /// <summary>
    /// 移动速度
    /// </summary>
    public float MoveSpeed;
    /// <summary>
    /// 经验
    /// </summary>
    public int DropExp;
    /// <summary>
    /// 掉落ID
    /// </summary>
    public int DropItemID;
    /// <summary>
    /// 伤害减免
    /// </summary>
    public int DamageReduction;
    /// <summary>
    /// 怪物血条长度系数
    /// </summary>
    public float HpLengthRatio;
    /// <summary>
    /// 初始属性_1_ID
    /// </summary>
    public System.Collections.Generic.List<AttrModifuerData> DefaultAttr;
    /// <summary>
    /// 技能_1
    /// </summary>
    public System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 附身技能
    /// </summary>
    public int AttachSkill;
    /// <summary>
    /// 循环播放技能
    /// </summary>
    public int AutoPlaySkill;
    /// <summary>
    /// AI行为ID
    /// </summary>
    public int AITaskID;
    /// <summary>
    /// 描边大小
    /// </summary>
    public int OutLineWidth;
    /// <summary>
    /// 描边颜色
    /// </summary>
    public string OutLineColor;

    public const int __ID__ = -55174244;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DefaultAttr) { _e?.ResolveRef(tables); }
    }


    public void CopyTo(ref MonsterConfig other)
    {
        if (other == null)
        {
            other = new MonsterConfig();
        }
        other.MonsterID = MonsterID;
        other.ModelID = ModelID;
        other.MonsterNameId = MonsterNameId;
        other.AttrID = AttrID;
        other.Type = Type;
        other.ModelScale = ModelScale;
        other.DiedDestroyTime = DiedDestroyTime;
        other.Level = Level;
        other.Atk = Atk;
        other.Hp = Hp;
        other.IsShowHp = IsShowHp;
        other.HpCount = HpCount;
        other.MoveSpeed = MoveSpeed;
        other.DropExp = DropExp;
        other.DropItemID = DropItemID;
        other.DamageReduction = DamageReduction;
        other.HpLengthRatio = HpLengthRatio;
        other.DefaultAttr = DefaultAttr == null ? null : new System.Collections.Generic.List<AttrModifuerData>(); if (DefaultAttr != null) foreach (var _e in DefaultAttr) { var _copy = _e; _e?.CopyTo(ref _copy); other.DefaultAttr.Add(_copy); }
        other.Skills = Skills == null ? null : new System.Collections.Generic.List<int>(Skills);
        other.AttachSkill = AttachSkill;
        other.AutoPlaySkill = AutoPlaySkill;
        other.AITaskID = AITaskID;
        other.OutLineWidth = OutLineWidth;
        other.OutLineColor = OutLineColor;
    }

    public MonsterConfig DeepCopy()
    {
        var other = new MonsterConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "MonsterID:" + MonsterID + ","
        + "ModelID:" + ModelID + ","
        + "MonsterNameId:" + MonsterNameId + ","
        + "AttrID:" + AttrID + ","
        + "Type:" + Type + ","
        + "ModelScale:" + ModelScale + ","
        + "DiedDestroyTime:" + DiedDestroyTime + ","
        + "Level:" + Level + ","
        + "Atk:" + Atk + ","
        + "Hp:" + Hp + ","
        + "IsShowHp:" + IsShowHp + ","
        + "HpCount:" + HpCount + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "DropExp:" + DropExp + ","
        + "DropItemID:" + DropItemID + ","
        + "DamageReduction:" + DamageReduction + ","
        + "HpLengthRatio:" + HpLengthRatio + ","
        + "DefaultAttr:" + Luban.StringUtil.CollectionToString(DefaultAttr) + ","
        + "Skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "AttachSkill:" + AttachSkill + ","
        + "AutoPlaySkill:" + AutoPlaySkill + ","
        + "AITaskID:" + AITaskID + ","
        + "OutLineWidth:" + OutLineWidth + ","
        + "OutLineColor:" + OutLineColor + ","
        + "}";
    }
}
}

