
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 路径点配置表
/// </summary>
public sealed partial class PathConfig : Luban.BeanBase
{
    public PathConfig() { }
    
    public PathConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        GroupID = _buf.ReadInt();
        MonsterPos = global::GameProto.Pos.DeserializePos(_buf);
        MonsterFlagPos = global::GameProto.Pos.DeserializePos(_buf);
        PortalPos = global::GameProto.Pos.DeserializePos(_buf);
        WaveArrowPos = global::GameProto.Pos.DeserializePos(_buf);
        WaveArrowRot = _buf.ReadFloat();
        MaxRadius = _buf.ReadFloat();
        PathCnt = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PathList = new System.Collections.Generic.List<Pos>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Pos _e0;  _e0 = global::GameProto.Pos.DeserializePos(_buf); PathList.Add(_e0);}}
        NextID = _buf.ReadInt();
        PrevID = _buf.ReadInt();
    }

    public static PathConfig DeserializePathConfig(ByteBuf _buf)
    {
        return new PathConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 组ID
    /// </summary>
    public int GroupID;
    /// <summary>
    /// 怪物出生点_X
    /// </summary>
    public Pos MonsterPos;
    /// <summary>
    /// 出生点旗帜位置_X
    /// </summary>
    public Pos MonsterFlagPos;
    /// <summary>
    /// 传送门位置_X
    /// </summary>
    public Pos PortalPos;
    /// <summary>
    /// 波次箭头位置_X
    /// </summary>
    public Pos WaveArrowPos;
    /// <summary>
    /// 波次箭头旋转角度
    /// </summary>
    public float WaveArrowRot;
    /// <summary>
    /// 范围半径
    /// </summary>
    public float MaxRadius;
    /// <summary>
    /// 路径点数量
    /// </summary>
    public int PathCnt;
    /// <summary>
    /// 怪物路径点_1_X
    /// </summary>
    public System.Collections.Generic.List<Pos> PathList;
    /// <summary>
    /// 下一跳转点
    /// </summary>
    public int NextID;
    /// <summary>
    /// 上一跳转点
    /// </summary>
    public int PrevID;

    public const int __ID__ = -1927921689;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref PathConfig other)
    {
        if (other == null)
        {
            other = new PathConfig();
        }
        other.ID = ID;
        other.GroupID = GroupID;
        other.MonsterPos = MonsterPos;
        other.MonsterFlagPos = MonsterFlagPos;
        other.PortalPos = PortalPos;
        other.WaveArrowPos = WaveArrowPos;
        other.WaveArrowRot = WaveArrowRot;
        other.MaxRadius = MaxRadius;
        other.PathCnt = PathCnt;
        other.PathList = PathList == null ? null : new System.Collections.Generic.List<Pos>(PathList);
        other.NextID = NextID;
        other.PrevID = PrevID;
    }

    public PathConfig DeepCopy()
    {
        var other = new PathConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "GroupID:" + GroupID + ","
        + "MonsterPos:" + MonsterPos + ","
        + "MonsterFlagPos:" + MonsterFlagPos + ","
        + "PortalPos:" + PortalPos + ","
        + "WaveArrowPos:" + WaveArrowPos + ","
        + "WaveArrowRot:" + WaveArrowRot + ","
        + "MaxRadius:" + MaxRadius + ","
        + "PathCnt:" + PathCnt + ","
        + "PathList:" + Luban.StringUtil.CollectionToString(PathList) + ","
        + "NextID:" + NextID + ","
        + "PrevID:" + PrevID + ","
        + "}";
    }
}
}

