
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 角色模型配对表
/// </summary>
public sealed partial class PlayerModelPairConfig : Luban.BeanBase
{
    public PlayerModelPairConfig() { }
    
    public PlayerModelPairConfig(ByteBuf _buf) 
    {
        RoleBodyType = _buf.ReadInt();
        ClothID = _buf.ReadInt();
        ModelID = _buf.ReadInt();
    }

    public static PlayerModelPairConfig DeserializePlayerModelPairConfig(ByteBuf _buf)
    {
        return new PlayerModelPairConfig(_buf);
    }

    /// <summary>
    /// 主角体形
    /// </summary>
    public int RoleBodyType;
    /// <summary>
    /// 时装ID
    /// </summary>
    public int ClothID;
    /// <summary>
    /// 模型ID
    /// </summary>
    public int ModelID;

    public const int __ID__ = -421483132;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref PlayerModelPairConfig other)
    {
        if (other == null)
        {
            other = new PlayerModelPairConfig();
        }
        other.RoleBodyType = RoleBodyType;
        other.ClothID = ClothID;
        other.ModelID = ModelID;
    }

    public PlayerModelPairConfig DeepCopy()
    {
        var other = new PlayerModelPairConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "RoleBodyType:" + RoleBodyType + ","
        + "ClothID:" + ClothID + ","
        + "ModelID:" + ModelID + ","
        + "}";
    }
}
}

