
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 音效随机配置表
/// </summary>
public sealed partial class SoundRandomConfig : Luban.BeanBase
{
    public SoundRandomConfig() { }
    
    public SoundRandomConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        SoundID = _buf.ReadInt();
        Location = _buf.ReadString();
        Weight = _buf.ReadFloat();
    }

    public static SoundRandomConfig DeserializeSoundRandomConfig(ByteBuf _buf)
    {
        return new SoundRandomConfig(_buf);
    }

    /// <summary>
    /// 变体ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 音效ID
    /// </summary>
    public int SoundID;
    /// <summary>
    /// 音频地址
    /// </summary>
    public string Location;
    /// <summary>
    /// 随机权重
    /// </summary>
    public float Weight;

    public const int __ID__ = 205239412;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref SoundRandomConfig other)
    {
        if (other == null)
        {
            other = new SoundRandomConfig();
        }
        other.ID = ID;
        other.SoundID = SoundID;
        other.Location = Location;
        other.Weight = Weight;
    }

    public SoundRandomConfig DeepCopy()
    {
        var other = new SoundRandomConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SoundID:" + SoundID + ","
        + "Location:" + Location + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}
}

