
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 武器模型配置表
/// </summary>
public sealed partial class WeaponModelConfig : Luban.BeanBase
{
    public WeaponModelConfig() { }
    
    public WeaponModelConfig(ByteBuf _buf) 
    {
        ModelID = _buf.ReadInt();
        UISpineLocation = _buf.ReadString();
        ModelLocation = _buf.ReadString();
        DummyPoint = _buf.ReadString();
        EffectID = _buf.ReadInt();
        ModelSortingOrder = _buf.ReadInt();
        UIAnimName = _buf.ReadString();
        RotateZ = _buf.ReadFloat();
        ShowType = _buf.ReadByte();
        FirePosLen = _buf.ReadFloat();
        UIOffsetX = _buf.ReadFloat();
        UIOffsetY = _buf.ReadFloat();
        UIScale = _buf.ReadFloat();
    }

    public static WeaponModelConfig DeserializeWeaponModelConfig(ByteBuf _buf)
    {
        return new WeaponModelConfig(_buf);
    }

    /// <summary>
    /// 模型ID
    /// </summary>
    public int ModelID;
    /// <summary>
    /// UISpine可寻址地址
    /// </summary>
    public string UISpineLocation;
    /// <summary>
    /// Model可寻址地址
    /// </summary>
    public string ModelLocation;
    /// <summary>
    /// 模型挂点
    /// </summary>
    public string DummyPoint;
    /// <summary>
    /// 特效ID
    /// </summary>
    public int EffectID;
    /// <summary>
    /// 模型层级
    /// </summary>
    public int ModelSortingOrder;
    /// <summary>
    /// 显示动画名
    /// </summary>
    public string UIAnimName;
    /// <summary>
    /// Z轴旋转
    /// </summary>
    public float RotateZ;
    /// <summary>
    /// 显示类型
    /// </summary>
    public byte ShowType;
    /// <summary>
    /// 开火位置偏移
    /// </summary>
    public float FirePosLen;
    /// <summary>
    /// UI偏移X轴
    /// </summary>
    public float UIOffsetX;
    /// <summary>
    /// UI偏移Y轴
    /// </summary>
    public float UIOffsetY;
    /// <summary>
    /// UI缩放
    /// </summary>
    public float UIScale;

    public const int __ID__ = 1670423535;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref WeaponModelConfig other)
    {
        if (other == null)
        {
            other = new WeaponModelConfig();
        }
        other.ModelID = ModelID;
        other.UISpineLocation = UISpineLocation;
        other.ModelLocation = ModelLocation;
        other.DummyPoint = DummyPoint;
        other.EffectID = EffectID;
        other.ModelSortingOrder = ModelSortingOrder;
        other.UIAnimName = UIAnimName;
        other.RotateZ = RotateZ;
        other.ShowType = ShowType;
        other.FirePosLen = FirePosLen;
        other.UIOffsetX = UIOffsetX;
        other.UIOffsetY = UIOffsetY;
        other.UIScale = UIScale;
    }

    public WeaponModelConfig DeepCopy()
    {
        var other = new WeaponModelConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ModelID:" + ModelID + ","
        + "UISpineLocation:" + UISpineLocation + ","
        + "ModelLocation:" + ModelLocation + ","
        + "DummyPoint:" + DummyPoint + ","
        + "EffectID:" + EffectID + ","
        + "ModelSortingOrder:" + ModelSortingOrder + ","
        + "UIAnimName:" + UIAnimName + ","
        + "RotateZ:" + RotateZ + ","
        + "ShowType:" + ShowType + ","
        + "FirePosLen:" + FirePosLen + ","
        + "UIOffsetX:" + UIOffsetX + ","
        + "UIOffsetY:" + UIOffsetY + ","
        + "UIScale:" + UIScale + ","
        + "}";
    }
}
}

