
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 活动开启配置表
/// </summary>
public sealed partial class ActivityOpenConfig : Luban.BeanBase
{
    public ActivityOpenConfig() { }
    
    public ActivityOpenConfig(ByteBuf _buf) 
    {
        ActivityID = _buf.ReadInt();
        ActivityNameID = _buf.ReadInt();
        ActivityType = _buf.ReadInt();
        OpenType = (ActivityOpenType)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); OpenParamList = new System.Collections.Generic.List<long>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { long _e0;  _e0 = _buf.ReadLong(); OpenParamList.Add(_e0);}}
        OpenLevel = _buf.ReadInt();
        CreateRoleDays = _buf.ReadInt();
        CreateTimeStart = _buf.ReadLong();
        CreateTimeEnd = _buf.ReadLong();
        SortID = _buf.ReadInt();
    }

    public static ActivityOpenConfig DeserializeActivityOpenConfig(ByteBuf _buf)
    {
        return new ActivityOpenConfig(_buf);
    }

    /// <summary>
    /// 活动ID
    /// </summary>
    public int ActivityID;
    /// <summary>
    /// 活动名称ID
    /// </summary>
    public int ActivityNameID;
    /// <summary>
    /// 活动类型
    /// </summary>
    public int ActivityType;
    /// <summary>
    /// 开启类型
    /// </summary>
    public ActivityOpenType OpenType;
    /// <summary>
    /// 活动开启参数
    /// </summary>
    public System.Collections.Generic.List<long> OpenParamList;
    /// <summary>
    /// 开启等级
    /// </summary>
    public int OpenLevel;
    /// <summary>
    /// 创角天数限制
    /// </summary>
    public int CreateRoleDays;
    /// <summary>
    /// 创角活动开启时间
    /// </summary>
    public long CreateTimeStart;
    /// <summary>
    /// 创角活动结束时间
    /// </summary>
    public long CreateTimeEnd;
    /// <summary>
    /// 排序ID
    /// </summary>
    public int SortID;

    public const int __ID__ = 1751481019;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref ActivityOpenConfig other)
    {
        if (other == null)
        {
            other = new ActivityOpenConfig();
        }
        other.ActivityID = ActivityID;
        other.ActivityNameID = ActivityNameID;
        other.ActivityType = ActivityType;
        other.OpenType = OpenType;
        other.OpenParamList = OpenParamList == null ? null : new System.Collections.Generic.List<long>(OpenParamList);
        other.OpenLevel = OpenLevel;
        other.CreateRoleDays = CreateRoleDays;
        other.CreateTimeStart = CreateTimeStart;
        other.CreateTimeEnd = CreateTimeEnd;
        other.SortID = SortID;
    }

    public ActivityOpenConfig DeepCopy()
    {
        var other = new ActivityOpenConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ActivityID:" + ActivityID + ","
        + "ActivityNameID:" + ActivityNameID + ","
        + "ActivityType:" + ActivityType + ","
        + "OpenType:" + OpenType + ","
        + "OpenParamList:" + Luban.StringUtil.CollectionToString(OpenParamList) + ","
        + "OpenLevel:" + OpenLevel + ","
        + "CreateRoleDays:" + CreateRoleDays + ","
        + "CreateTimeStart:" + CreateTimeStart + ","
        + "CreateTimeEnd:" + CreateTimeEnd + ","
        + "SortID:" + SortID + ","
        + "}";
    }
}
}

