
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 章节配置表
/// </summary>
public sealed partial class ChapterConfig : Luban.BeanBase
{
    public ChapterConfig() { }
    
    public ChapterConfig(ByteBuf _buf) 
    {
        ChapterID = _buf.ReadInt();
        ChapterType = _buf.ReadInt();
        Difficult = _buf.ReadInt();
        GroupID = _buf.ReadInt();
        ChapterNum = _buf.ReadInt();
        MapID = _buf.ReadInt();
        ChapterNameID = _buf.ReadInt();
        IconName = _buf.ReadString();
        ModelPath = _buf.ReadString();
        GridIconName = _buf.ReadString();
        ChapterDescID = _buf.ReadInt();
        StageCount = _buf.ReadInt();
        MaxReliveCount = _buf.ReadInt();
        CreateDay = _buf.ReadInt();
        CreateDayCoef = _buf.ReadFloat();
        FailureCount = _buf.ReadInt();
        FailureDecayCoef = _buf.ReadFloat();
        FailureDecayCount = _buf.ReadInt();
        StartCostStam = _buf.ReadInt();
        IsSaoDangNeedFinChapter = _buf.ReadBool();
        UnlockLevel = _buf.ReadInt();
        FirstPassBootyID = _buf.ReadInt();
        FailBootyID = _buf.ReadInt();
        CanMultiPlayer = _buf.ReadBool();
        MultiPlayerCnt = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PassChapterCurrency = new System.Collections.Generic.List<PassChapterCurrency>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { PassChapterCurrency _e0;  _e0 = global::GameProto.PassChapterCurrency.DeserializePassChapterCurrency(_buf); PassChapterCurrency.Add(_e0);}}
        ShowBootyID = _buf.ReadInt();
        FinMaxGold = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ChapterHangDropItem = new System.Collections.Generic.List<ChapterHangDropItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ChapterHangDropItem _e0;  _e0 = global::GameProto.ChapterHangDropItem.DeserializeChapterHangDropItem(_buf); ChapterHangDropItem.Add(_e0);}}
        GuaJiBootyID = _buf.ReadInt();
        TourCostStam = _buf.ReadInt();
        TourBootyID = _buf.ReadInt();
        UnlockDescID = _buf.ReadInt();
        IsLocked = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); UnlockChapterCodition = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); UnlockChapterCodition.Add(_e0);}}
        {int n0 = _buf.ReadSize(); NextChapterList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NextChapterList.Add(_e0);}}
        RandomLibID = _buf.ReadInt();
        LvUpLibID = _buf.ReadInt();
        IsContinue = _buf.ReadBool();
        IsUseItem = _buf.ReadBool();
        IsPassContinue = _buf.ReadBool();
        SupportSpeedSwitching = _buf.ReadBool();
        IsSupportAd = _buf.ReadBool();
        MainPlayerPos = global::GameProto.Pos.DeserializePos(_buf);
        RefreshRequiredGoldNum = _buf.ReadInt();
    }

    public static ChapterConfig DeserializeChapterConfig(ByteBuf _buf)
    {
        return new ChapterConfig(_buf);
    }

    /// <summary>
    /// 章节ID
    /// </summary>
    public int ChapterID;
    /// <summary>
    /// 章节类型
    /// </summary>
    public int ChapterType;
    /// <summary>
    /// 难度类型
    /// </summary>
    public int Difficult;
    /// <summary>
    /// 章节组ID
    /// </summary>
    public int GroupID;
    /// <summary>
    /// 章节组编号
    /// </summary>
    public int ChapterNum;
    /// <summary>
    /// 地图ID
    /// </summary>
    public int MapID;
    /// <summary>
    /// 章节名称ID
    /// </summary>
    public int ChapterNameID;
    /// <summary>
    /// 章节图片
    /// </summary>
    public string IconName;
    /// <summary>
    /// 章节模型
    /// </summary>
    public string ModelPath;
    /// <summary>
    /// 格子图片
    /// </summary>
    public string GridIconName;
    /// <summary>
    /// 章节描述ID
    /// </summary>
    public int ChapterDescID;
    /// <summary>
    /// 关卡个数
    /// </summary>
    public int StageCount;
    /// <summary>
    /// 最大复活次数
    /// </summary>
    public int MaxReliveCount;
    /// <summary>
    /// 创角天数
    /// </summary>
    public int CreateDay;
    /// <summary>
    /// 创角天数系数
    /// </summary>
    public float CreateDayCoef;
    /// <summary>
    /// 累计失败次数
    /// </summary>
    public int FailureCount;
    /// <summary>
    /// 累计失败每次衰减系数
    /// </summary>
    public float FailureDecayCoef;
    /// <summary>
    /// 累计失败衰减次数上限
    /// </summary>
    public int FailureDecayCount;
    /// <summary>
    /// 开启消耗体力
    /// </summary>
    public int StartCostStam;
    /// <summary>
    /// 是否判断完成章节
    /// </summary>
    public bool IsSaoDangNeedFinChapter;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public int UnlockLevel;
    /// <summary>
    /// 首次通关奖励
    /// </summary>
    public int FirstPassBootyID;
    /// <summary>
    /// 失败奖励
    /// </summary>
    public int FailBootyID;
    /// <summary>
    /// 是否支持多人模式
    /// </summary>
    public bool CanMultiPlayer;
    /// <summary>
    /// 多人模式组队人数
    /// </summary>
    public int MultiPlayerCnt;
    /// <summary>
    /// 通关货币类型
    /// </summary>
    public System.Collections.Generic.List<PassChapterCurrency> PassChapterCurrency;
    /// <summary>
    /// 局外显示奖励
    /// </summary>
    public int ShowBootyID;
    /// <summary>
    /// 最大金币获取
    /// </summary>
    public int FinMaxGold;
    /// <summary>
    /// 挂机道具类型
    /// </summary>
    public System.Collections.Generic.List<ChapterHangDropItem> ChapterHangDropItem;
    /// <summary>
    /// 挂机奖励ID
    /// </summary>
    public int GuaJiBootyID;
    /// <summary>
    /// 游历消耗体力
    /// </summary>
    public int TourCostStam;
    /// <summary>
    /// 游历奖励ID
    /// </summary>
    public int TourBootyID;
    /// <summary>
    /// 解锁条件描述ID
    /// </summary>
    public int UnlockDescID;
    /// <summary>
    /// 是否锁定状态
    /// </summary>
    public bool IsLocked;
    /// <summary>
    /// 解锁条件章节
    /// </summary>
    public System.Collections.Generic.List<int> UnlockChapterCodition;
    /// <summary>
    /// 通关解锁章节ID
    /// </summary>
    public System.Collections.Generic.List<int> NextChapterList;
    /// <summary>
    /// 开局随机库ID
    /// </summary>
    public int RandomLibID;
    /// <summary>
    /// 升级库ID
    /// </summary>
    public int LvUpLibID;
    /// <summary>
    /// 是否断线重连
    /// </summary>
    public bool IsContinue;
    /// <summary>
    /// 是否使用道具
    /// </summary>
    public bool IsUseItem;
    /// <summary>
    /// 通关是否继续挑战
    /// </summary>
    public bool IsPassContinue;
    /// <summary>
    /// 是否支持倍速切换
    /// </summary>
    public bool SupportSpeedSwitching;
    /// <summary>
    /// 是否支持广告
    /// </summary>
    public bool IsSupportAd;
    /// <summary>
    /// 主角位置_X，Y
    /// </summary>
    public Pos MainPlayerPos;
    /// <summary>
    /// 刷背包物件的金币基础消耗
    /// </summary>
    public int RefreshRequiredGoldNum;

    public const int __ID__ = 155381199;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in PassChapterCurrency) { _e?.ResolveRef(tables); }
        foreach (var _e in ChapterHangDropItem) { _e?.ResolveRef(tables); }
    }


    public void CopyTo(ref ChapterConfig other)
    {
        if (other == null)
        {
            other = new ChapterConfig();
        }
        other.ChapterID = ChapterID;
        other.ChapterType = ChapterType;
        other.Difficult = Difficult;
        other.GroupID = GroupID;
        other.ChapterNum = ChapterNum;
        other.MapID = MapID;
        other.ChapterNameID = ChapterNameID;
        other.IconName = IconName;
        other.ModelPath = ModelPath;
        other.GridIconName = GridIconName;
        other.ChapterDescID = ChapterDescID;
        other.StageCount = StageCount;
        other.MaxReliveCount = MaxReliveCount;
        other.CreateDay = CreateDay;
        other.CreateDayCoef = CreateDayCoef;
        other.FailureCount = FailureCount;
        other.FailureDecayCoef = FailureDecayCoef;
        other.FailureDecayCount = FailureDecayCount;
        other.StartCostStam = StartCostStam;
        other.IsSaoDangNeedFinChapter = IsSaoDangNeedFinChapter;
        other.UnlockLevel = UnlockLevel;
        other.FirstPassBootyID = FirstPassBootyID;
        other.FailBootyID = FailBootyID;
        other.CanMultiPlayer = CanMultiPlayer;
        other.MultiPlayerCnt = MultiPlayerCnt;
        other.PassChapterCurrency = PassChapterCurrency == null ? null : new System.Collections.Generic.List<PassChapterCurrency>(); if (PassChapterCurrency != null) foreach (var _e in PassChapterCurrency) { var _copy = _e; _e?.CopyTo(ref _copy); other.PassChapterCurrency.Add(_copy); }
        other.ShowBootyID = ShowBootyID;
        other.FinMaxGold = FinMaxGold;
        other.ChapterHangDropItem = ChapterHangDropItem == null ? null : new System.Collections.Generic.List<ChapterHangDropItem>(); if (ChapterHangDropItem != null) foreach (var _e in ChapterHangDropItem) { var _copy = _e; _e?.CopyTo(ref _copy); other.ChapterHangDropItem.Add(_copy); }
        other.GuaJiBootyID = GuaJiBootyID;
        other.TourCostStam = TourCostStam;
        other.TourBootyID = TourBootyID;
        other.UnlockDescID = UnlockDescID;
        other.IsLocked = IsLocked;
        other.UnlockChapterCodition = UnlockChapterCodition == null ? null : new System.Collections.Generic.List<int>(UnlockChapterCodition);
        other.NextChapterList = NextChapterList == null ? null : new System.Collections.Generic.List<int>(NextChapterList);
        other.RandomLibID = RandomLibID;
        other.LvUpLibID = LvUpLibID;
        other.IsContinue = IsContinue;
        other.IsUseItem = IsUseItem;
        other.IsPassContinue = IsPassContinue;
        other.SupportSpeedSwitching = SupportSpeedSwitching;
        other.IsSupportAd = IsSupportAd;
        other.MainPlayerPos = MainPlayerPos;
        other.RefreshRequiredGoldNum = RefreshRequiredGoldNum;
    }

    public ChapterConfig DeepCopy()
    {
        var other = new ChapterConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ChapterID:" + ChapterID + ","
        + "ChapterType:" + ChapterType + ","
        + "Difficult:" + Difficult + ","
        + "GroupID:" + GroupID + ","
        + "ChapterNum:" + ChapterNum + ","
        + "MapID:" + MapID + ","
        + "ChapterNameID:" + ChapterNameID + ","
        + "IconName:" + IconName + ","
        + "ModelPath:" + ModelPath + ","
        + "GridIconName:" + GridIconName + ","
        + "ChapterDescID:" + ChapterDescID + ","
        + "StageCount:" + StageCount + ","
        + "MaxReliveCount:" + MaxReliveCount + ","
        + "CreateDay:" + CreateDay + ","
        + "CreateDayCoef:" + CreateDayCoef + ","
        + "FailureCount:" + FailureCount + ","
        + "FailureDecayCoef:" + FailureDecayCoef + ","
        + "FailureDecayCount:" + FailureDecayCount + ","
        + "StartCostStam:" + StartCostStam + ","
        + "IsSaoDangNeedFinChapter:" + IsSaoDangNeedFinChapter + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "FirstPassBootyID:" + FirstPassBootyID + ","
        + "FailBootyID:" + FailBootyID + ","
        + "CanMultiPlayer:" + CanMultiPlayer + ","
        + "MultiPlayerCnt:" + MultiPlayerCnt + ","
        + "PassChapterCurrency:" + Luban.StringUtil.CollectionToString(PassChapterCurrency) + ","
        + "ShowBootyID:" + ShowBootyID + ","
        + "FinMaxGold:" + FinMaxGold + ","
        + "ChapterHangDropItem:" + Luban.StringUtil.CollectionToString(ChapterHangDropItem) + ","
        + "GuaJiBootyID:" + GuaJiBootyID + ","
        + "TourCostStam:" + TourCostStam + ","
        + "TourBootyID:" + TourBootyID + ","
        + "UnlockDescID:" + UnlockDescID + ","
        + "IsLocked:" + IsLocked + ","
        + "UnlockChapterCodition:" + Luban.StringUtil.CollectionToString(UnlockChapterCodition) + ","
        + "NextChapterList:" + Luban.StringUtil.CollectionToString(NextChapterList) + ","
        + "RandomLibID:" + RandomLibID + ","
        + "LvUpLibID:" + LvUpLibID + ","
        + "IsContinue:" + IsContinue + ","
        + "IsUseItem:" + IsUseItem + ","
        + "IsPassContinue:" + IsPassContinue + ","
        + "supportSpeedSwitching:" + SupportSpeedSwitching + ","
        + "IsSupportAd:" + IsSupportAd + ","
        + "MainPlayerPos:" + MainPlayerPos + ","
        + "RefreshRequiredGoldNum:" + RefreshRequiredGoldNum + ","
        + "}";
    }
}
}

