
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 特效配置表
/// </summary>
public sealed partial class EffectConfig : Luban.BeanBase
{
    public EffectConfig() { }
    
    public EffectConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Location = _buf.ReadString();
        Duration = _buf.ReadFloat();
        Scale = _buf.ReadFloat();
        DelayDestroy = _buf.ReadFloat();
    }

    public static EffectConfig DeserializeEffectConfig(ByteBuf _buf)
    {
        return new EffectConfig(_buf);
    }

    /// <summary>
    /// 特效ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 特效可寻址地址
    /// </summary>
    public string Location;
    /// <summary>
    /// 持续时间
    /// </summary>
    public float Duration;
    /// <summary>
    /// 缩放比例
    /// </summary>
    public float Scale;
    /// <summary>
    /// 延迟销毁时间
    /// </summary>
    public float DelayDestroy;

    public const int __ID__ = -682668973;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref EffectConfig other)
    {
        if (other == null)
        {
            other = new EffectConfig();
        }
        other.ID = ID;
        other.Location = Location;
        other.Duration = Duration;
        other.Scale = Scale;
        other.DelayDestroy = DelayDestroy;
    }

    public EffectConfig DeepCopy()
    {
        var other = new EffectConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Location:" + Location + ","
        + "Duration:" + Duration + ","
        + "Scale:" + Scale + ","
        + "DelayDestroy:" + DelayDestroy + ","
        + "}";
    }
}
}

