
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 功能参数配置表
/// </summary>
public sealed partial class FuncParamConfig : Luban.BeanBase
{
    public FuncParamConfig() { }
    
    public FuncParamConfig(ByteBuf _buf) 
    {
        AccountTokenPublicKeyPem = _buf.ReadString();
        AccountTokenPrivateKeyPem = _buf.ReadString();
        AccountTokenExpireTime = _buf.ReadInt();
        AccountValidIssuer = _buf.ReadString();
        AccountValidAudience = _buf.ReadString();
        AccountRegisterSessionLifeTime = _buf.ReadInt();
        RecentServerMaxCount = _buf.ReadInt();
        OldSessionLifeTime = _buf.ReadInt();
        DelayOfflineTime = _buf.ReadInt();
        PlayerInitConfigID = _buf.ReadInt();
        RoleNameChineseMinCount = _buf.ReadInt();
        RoleNameChineseMaxCount = _buf.ReadInt();
        RoleNameLatinMinCount = _buf.ReadInt();
        RoleNameLatinMaxCount = _buf.ReadInt();
        RoleNameMixedMinCount = _buf.ReadInt();
        RoleNameMixedMaxCount = _buf.ReadInt();
        RoleNameDigitMinCount = _buf.ReadInt();
        RoleNameDigitMaxCount = _buf.ReadInt();
        AuthenticationAddress = _buf.ReadString();
        AuthenticationPort = _buf.ReadInt();
        DefaultMaleModelID = _buf.ReadInt();
        DefaultFemaleModelID = _buf.ReadInt();
        DefaultGunFashionID = _buf.ReadInt();
    }

    public static FuncParamConfig DeserializeFuncParamConfig(ByteBuf _buf)
    {
        return new FuncParamConfig(_buf);
    }

    /// <summary>
    /// 账号Token公钥
    /// </summary>
    public string AccountTokenPublicKeyPem;
    /// <summary>
    /// 账号Token私钥
    /// </summary>
    public string AccountTokenPrivateKeyPem;
    /// <summary>
    /// 账号Token过期时间(毫秒)
    /// </summary>
    public int AccountTokenExpireTime;
    /// <summary>
    /// 发证者
    /// </summary>
    public string AccountValidIssuer;
    /// <summary>
    /// 受众
    /// </summary>
    public string AccountValidAudience;
    /// <summary>
    /// 注册Session的延迟销毁时间(毫秒)(短链接)
    /// </summary>
    public int AccountRegisterSessionLifeTime;
    /// <summary>
    /// 记录服务器最近登录最大个数
    /// </summary>
    public int RecentServerMaxCount;
    /// <summary>
    /// 断线重连时旧的Session生命周期(毫秒)
    /// </summary>
    public int OldSessionLifeTime;
    /// <summary>
    /// 延迟下线时间(毫秒)
    /// </summary>
    public int DelayOfflineTime;
    /// <summary>
    /// 玩家创建账号的初始角色配置ID
    /// </summary>
    public int PlayerInitConfigID;
    /// <summary>
    /// 纯中文模式下最少字符数
    /// </summary>
    public int RoleNameChineseMinCount;
    /// <summary>
    /// 纯中文模式下最多字符数
    /// </summary>
    public int RoleNameChineseMaxCount;
    /// <summary>
    /// 纯英文模式下最少字符数
    /// </summary>
    public int RoleNameLatinMinCount;
    /// <summary>
    /// 纯英文模式下最多字符数
    /// </summary>
    public int RoleNameLatinMaxCount;
    /// <summary>
    /// 混排模式下最少字符数
    /// </summary>
    public int RoleNameMixedMinCount;
    /// <summary>
    /// 混排模式下最多字符数
    /// </summary>
    public int RoleNameMixedMaxCount;
    /// <summary>
    /// 纯数字模式下最少字符数
    /// </summary>
    public int RoleNameDigitMinCount;
    /// <summary>
    /// 纯数字模式下最多字符数
    /// </summary>
    public int RoleNameDigitMaxCount;
    /// <summary>
    /// 鉴权服务器地址
    /// </summary>
    public string AuthenticationAddress;
    /// <summary>
    /// 鉴权服务器端口号
    /// </summary>
    public int AuthenticationPort;
    /// <summary>
    /// 男角色默认模型ID
    /// </summary>
    public int DefaultMaleModelID;
    /// <summary>
    /// 女角色默认模型ID
    /// </summary>
    public int DefaultFemaleModelID;
    /// <summary>
    /// 默认武器ID
    /// </summary>
    public int DefaultGunFashionID;

    public const int __ID__ = -1155611477;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref FuncParamConfig other)
    {
        if (other == null)
        {
            other = new FuncParamConfig();
        }
        other.AccountTokenPublicKeyPem = AccountTokenPublicKeyPem;
        other.AccountTokenPrivateKeyPem = AccountTokenPrivateKeyPem;
        other.AccountTokenExpireTime = AccountTokenExpireTime;
        other.AccountValidIssuer = AccountValidIssuer;
        other.AccountValidAudience = AccountValidAudience;
        other.AccountRegisterSessionLifeTime = AccountRegisterSessionLifeTime;
        other.RecentServerMaxCount = RecentServerMaxCount;
        other.OldSessionLifeTime = OldSessionLifeTime;
        other.DelayOfflineTime = DelayOfflineTime;
        other.PlayerInitConfigID = PlayerInitConfigID;
        other.RoleNameChineseMinCount = RoleNameChineseMinCount;
        other.RoleNameChineseMaxCount = RoleNameChineseMaxCount;
        other.RoleNameLatinMinCount = RoleNameLatinMinCount;
        other.RoleNameLatinMaxCount = RoleNameLatinMaxCount;
        other.RoleNameMixedMinCount = RoleNameMixedMinCount;
        other.RoleNameMixedMaxCount = RoleNameMixedMaxCount;
        other.RoleNameDigitMinCount = RoleNameDigitMinCount;
        other.RoleNameDigitMaxCount = RoleNameDigitMaxCount;
        other.AuthenticationAddress = AuthenticationAddress;
        other.AuthenticationPort = AuthenticationPort;
        other.DefaultMaleModelID = DefaultMaleModelID;
        other.DefaultFemaleModelID = DefaultFemaleModelID;
        other.DefaultGunFashionID = DefaultGunFashionID;
    }

    public FuncParamConfig DeepCopy()
    {
        var other = new FuncParamConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "AccountTokenPublicKeyPem:" + AccountTokenPublicKeyPem + ","
        + "AccountTokenPrivateKeyPem:" + AccountTokenPrivateKeyPem + ","
        + "AccountTokenExpireTime:" + AccountTokenExpireTime + ","
        + "AccountValidIssuer:" + AccountValidIssuer + ","
        + "AccountValidAudience:" + AccountValidAudience + ","
        + "AccountRegisterSessionLifeTime:" + AccountRegisterSessionLifeTime + ","
        + "RecentServerMaxCount:" + RecentServerMaxCount + ","
        + "OldSessionLifeTime:" + OldSessionLifeTime + ","
        + "DelayOfflineTime:" + DelayOfflineTime + ","
        + "PlayerInitConfigID:" + PlayerInitConfigID + ","
        + "RoleNameChineseMinCount:" + RoleNameChineseMinCount + ","
        + "RoleNameChineseMaxCount:" + RoleNameChineseMaxCount + ","
        + "RoleNameLatinMinCount:" + RoleNameLatinMinCount + ","
        + "RoleNameLatinMaxCount:" + RoleNameLatinMaxCount + ","
        + "RoleNameMixedMinCount:" + RoleNameMixedMinCount + ","
        + "RoleNameMixedMaxCount:" + RoleNameMixedMaxCount + ","
        + "RoleNameDigitMinCount:" + RoleNameDigitMinCount + ","
        + "RoleNameDigitMaxCount:" + RoleNameDigitMaxCount + ","
        + "AuthenticationAddress:" + AuthenticationAddress + ","
        + "AuthenticationPort:" + AuthenticationPort + ","
        + "DefaultMaleModelID:" + DefaultMaleModelID + ","
        + "DefaultFemaleModelID:" + DefaultFemaleModelID + ","
        + "DefaultGunFashionID:" + DefaultGunFashionID + ","
        + "}";
    }
}
}

