
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// GM配置表
/// </summary>
public sealed partial class GmConfig : Luban.BeanBase
{
    public GmConfig() { }
    
    public GmConfig(ByteBuf _buf) 
    {
        GmID = _buf.ReadInt();
        GmType = _buf.ReadInt();
        GmDesc = _buf.ReadString();
        GmOrder = _buf.ReadString();
        OrderID = _buf.ReadInt();
        Num = _buf.ReadInt();
        ExecuteDirectly = _buf.ReadBool();
        ExecuteClose = _buf.ReadBool();
        AssConfig = _buf.ReadInt();
    }

    public static GmConfig DeserializeGmConfig(ByteBuf _buf)
    {
        return new GmConfig(_buf);
    }

    /// <summary>
    /// GMID
    /// </summary>
    public int GmID;
    /// <summary>
    /// Gm类型（1:客户端，2:服务器）
    /// </summary>
    public int GmType;
    /// <summary>
    /// 描述（按钮名）
    /// </summary>
    public string GmDesc;
    /// <summary>
    /// GM命令
    /// </summary>
    public string GmOrder;
    /// <summary>
    /// 命令ID
    /// </summary>
    public int OrderID;
    /// <summary>
    /// 数量
    /// </summary>
    public int Num;
    /// <summary>
    /// 是否直接执行
    /// </summary>
    public bool ExecuteDirectly;
    /// <summary>
    /// 是否执行后关闭
    /// </summary>
    public bool ExecuteClose;
    /// <summary>
    /// 关联配置
    /// </summary>
    public int AssConfig;

    public const int __ID__ = -836822040;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref GmConfig other)
    {
        if (other == null)
        {
            other = new GmConfig();
        }
        other.GmID = GmID;
        other.GmType = GmType;
        other.GmDesc = GmDesc;
        other.GmOrder = GmOrder;
        other.OrderID = OrderID;
        other.Num = Num;
        other.ExecuteDirectly = ExecuteDirectly;
        other.ExecuteClose = ExecuteClose;
        other.AssConfig = AssConfig;
    }

    public GmConfig DeepCopy()
    {
        var other = new GmConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "GmID:" + GmID + ","
        + "GmType:" + GmType + ","
        + "GmDesc:" + GmDesc + ","
        + "GmOrder:" + GmOrder + ","
        + "OrderID:" + OrderID + ","
        + "Num:" + Num + ","
        + "ExecuteDirectly:" + ExecuteDirectly + ","
        + "ExecuteClose:" + ExecuteClose + ","
        + "AssConfig:" + AssConfig + ","
        + "}";
    }
}
}

