
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 地图配置表
/// </summary>
public sealed partial class MapConfig : Luban.BeanBase
{
    public MapConfig() { }
    
    public MapConfig(ByteBuf _buf) 
    {
        MapID = _buf.ReadInt();
        MapResPath = _buf.ReadString();
        GridResPath = _buf.ReadString();
        GridIcon = _buf.ReadString();
        BornPosEffID = _buf.ReadInt();
        WaveTipPos = global::GameProto.Pos.DeserializePos(_buf);
        BattleCenter = global::GameProto.Pos.DeserializePos(_buf);
        {int n0 = _buf.ReadSize(); PathList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PathList.Add(_e0);}}
    }

    public static MapConfig DeserializeMapConfig(ByteBuf _buf)
    {
        return new MapConfig(_buf);
    }

    /// <summary>
    /// 地图ID
    /// </summary>
    public int MapID;
    /// <summary>
    /// 地图资源
    /// </summary>
    public string MapResPath;
    /// <summary>
    /// 格子资源
    /// </summary>
    public string GridResPath;
    /// <summary>
    /// 格子图片
    /// </summary>
    public string GridIcon;
    /// <summary>
    /// 出生点特效ID
    /// </summary>
    public int BornPosEffID;
    /// <summary>
    /// 波次提示位置_X
    /// </summary>
    public Pos WaveTipPos;
    /// <summary>
    /// 战场中心_X
    /// </summary>
    public Pos BattleCenter;
    /// <summary>
    /// 路径点_1
    /// </summary>
    public System.Collections.Generic.List<int> PathList;

    public const int __ID__ = -1840922722;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref MapConfig other)
    {
        if (other == null)
        {
            other = new MapConfig();
        }
        other.MapID = MapID;
        other.MapResPath = MapResPath;
        other.GridResPath = GridResPath;
        other.GridIcon = GridIcon;
        other.BornPosEffID = BornPosEffID;
        other.WaveTipPos = WaveTipPos;
        other.BattleCenter = BattleCenter;
        other.PathList = PathList == null ? null : new System.Collections.Generic.List<int>(PathList);
    }

    public MapConfig DeepCopy()
    {
        var other = new MapConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "MapID:" + MapID + ","
        + "MapResPath:" + MapResPath + ","
        + "GridResPath:" + GridResPath + ","
        + "GridIcon:" + GridIcon + ","
        + "BornPosEffID:" + BornPosEffID + ","
        + "WaveTipPos:" + WaveTipPos + ","
        + "BattleCenter:" + BattleCenter + ","
        + "PathList:" + Luban.StringUtil.CollectionToString(PathList) + ","
        + "}";
    }
}
}

