
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 角色初始配置表
/// </summary>
public sealed partial class PlayerInitConfig : Luban.BeanBase
{
    public PlayerInitConfig() { }
    
    public PlayerInitConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Sex = _buf.ReadByte();
        Level = _buf.ReadInt();
        Exp = _buf.ReadInt();
        HeadID = _buf.ReadInt();
        FightValue = _buf.ReadInt();
        Diamond = _buf.ReadInt();
        Gold = _buf.ReadInt();
        Stam = _buf.ReadInt();
        IsFinGuide = _buf.ReadByte();
        Sign = _buf.ReadString();
    }

    public static PlayerInitConfig DeserializePlayerInitConfig(ByteBuf _buf)
    {
        return new PlayerInitConfig(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 初始性别
    /// </summary>
    public byte Sex;
    /// <summary>
    /// 初始等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 初始经验
    /// </summary>
    public int Exp;
    /// <summary>
    /// 初始头像ID
    /// </summary>
    public int HeadID;
    /// <summary>
    /// 初始战斗力
    /// </summary>
    public int FightValue;
    /// <summary>
    /// 初始钻石
    /// </summary>
    public int Diamond;
    /// <summary>
    /// 初始金币
    /// </summary>
    public int Gold;
    /// <summary>
    /// 初始体力
    /// </summary>
    public int Stam;
    /// <summary>
    /// 是否完成新手引导
    /// </summary>
    public byte IsFinGuide;
    /// <summary>
    /// 初始签名
    /// </summary>
    public string Sign;

    public const int __ID__ = 2025266771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref PlayerInitConfig other)
    {
        if (other == null)
        {
            other = new PlayerInitConfig();
        }
        other.ID = ID;
        other.Sex = Sex;
        other.Level = Level;
        other.Exp = Exp;
        other.HeadID = HeadID;
        other.FightValue = FightValue;
        other.Diamond = Diamond;
        other.Gold = Gold;
        other.Stam = Stam;
        other.IsFinGuide = IsFinGuide;
        other.Sign = Sign;
    }

    public PlayerInitConfig DeepCopy()
    {
        var other = new PlayerInitConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Sex:" + Sex + ","
        + "Level:" + Level + ","
        + "Exp:" + Exp + ","
        + "HeadID:" + HeadID + ","
        + "FightValue:" + FightValue + ","
        + "Diamond:" + Diamond + ","
        + "Gold:" + Gold + ","
        + "Stam:" + Stam + ","
        + "IsFinGuide:" + IsFinGuide + ","
        + "Sign:" + Sign + ","
        + "}";
    }
}
}

