
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 随机名配置表
/// </summary>
public sealed partial class RandomNameConfig : Luban.BeanBase
{
    public RandomNameConfig() { }
    
    public RandomNameConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
    }

    public static RandomNameConfig DeserializeRandomNameConfig(ByteBuf _buf)
    {
        return new RandomNameConfig(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;

    public const int __ID__ = 1869005552;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref RandomNameConfig other)
    {
        if (other == null)
        {
            other = new RandomNameConfig();
        }
        other.ID = ID;
        other.Name = Name;
    }

    public RandomNameConfig DeepCopy()
    {
        var other = new RandomNameConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "}";
    }
}
}

