
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 服务器状态配置表
/// </summary>
public sealed partial class ServerStateConfig : Luban.BeanBase
{
    public ServerStateConfig() { }
    
    public ServerStateConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        StateName = _buf.ReadString();
        Location = _buf.ReadString();
        Color = _buf.ReadString();
    }

    public static ServerStateConfig DeserializeServerStateConfig(ByteBuf _buf)
    {
        return new ServerStateConfig(_buf);
    }

    /// <summary>
    /// 服务器状态ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 状态名
    /// </summary>
    public string StateName;
    /// <summary>
    /// 图标
    /// </summary>
    public string Location;
    /// <summary>
    /// 状态颜色
    /// </summary>
    public string Color;

    public const int __ID__ = 1530553296;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref ServerStateConfig other)
    {
        if (other == null)
        {
            other = new ServerStateConfig();
        }
        other.ID = ID;
        other.StateName = StateName;
        other.Location = Location;
        other.Color = Color;
    }

    public ServerStateConfig DeepCopy()
    {
        var other = new ServerStateConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "StateName:" + StateName + ","
        + "Location:" + Location + ","
        + "Color:" + Color + ","
        + "}";
    }
}
}

