
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 服务器配置表
/// </summary>
public sealed partial class ServerConfig : Luban.BeanBase
{
    public ServerConfig() { }
    
    public ServerConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        WorldID = _buf.ReadInt();
        Name = _buf.ReadString();
        Address = _buf.ReadString();
        Port = _buf.ReadInt();
        Recommend = _buf.ReadBool();
        Group = _buf.ReadInt();
        State = _buf.ReadByte();
    }

    public static ServerConfig DeserializeServerConfig(ByteBuf _buf)
    {
        return new ServerConfig(_buf);
    }

    /// <summary>
    /// 服务器ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 世界ID
    /// </summary>
    public int WorldID;
    /// <summary>
    /// 服务器名字
    /// </summary>
    public string Name;
    /// <summary>
    /// 服务器地址
    /// </summary>
    public string Address;
    /// <summary>
    /// 服务器端口号
    /// </summary>
    public int Port;
    /// <summary>
    /// 推荐服务器
    /// </summary>
    public bool Recommend;
    /// <summary>
    /// 服务器分组
    /// </summary>
    public int Group;
    /// <summary>
    /// 服务器状态
    /// </summary>
    public byte State;

    public const int __ID__ = 1611936901;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref ServerConfig other)
    {
        if (other == null)
        {
            other = new ServerConfig();
        }
        other.ID = ID;
        other.WorldID = WorldID;
        other.Name = Name;
        other.Address = Address;
        other.Port = Port;
        other.Recommend = Recommend;
        other.Group = Group;
        other.State = State;
    }

    public ServerConfig DeepCopy()
    {
        var other = new ServerConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "WorldID:" + WorldID + ","
        + "Name:" + Name + ","
        + "Address:" + Address + ","
        + "Port:" + Port + ","
        + "Recommend:" + Recommend + ","
        + "Group:" + Group + ","
        + "State:" + State + ","
        + "}";
    }
}
}

