
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 文本配置表
/// </summary>
public sealed partial class TextConfig : Luban.BeanBase
{
    public TextConfig() { }
    
    public TextConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ArgNum = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); Content = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Content[__index0] = __e0;}}
    }

    public static TextConfig DeserializeTextConfig(ByteBuf _buf)
    {
        return new TextConfig(_buf);
    }

    /// <summary>
    /// 文本ID
    /// </summary>
    public int ID;
    /// <summary>
    /// 参数数量
    /// </summary>
    public int ArgNum;
    /// <summary>
    /// 内容是 string 数组类型，数组索引对应 LocalizationType 枚举
    /// </summary>
    public string[] Content;

    public const int __ID__ = -912442641;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref TextConfig other)
    {
        if (other == null)
        {
            other = new TextConfig();
        }
        other.ID = ID;
        other.ArgNum = ArgNum;
        other.Content = Content == null ? null : ((string[])Content.Clone());
    }

    public TextConfig DeepCopy()
    {
        var other = new TextConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ArgNum:" + ArgNum + ","
        + "Content:" + Luban.StringUtil.CollectionToString(Content) + ","
        + "}";
    }
}
}

